chainsimple: main.cpp 
	g++ -W -Wall -Werror -ansi -pedantic main.cpp HashTableChain.cpp HashTableProbe.cpp
	./a.out -1 -chain input1.txt
chainspell: main.cpp 
	g++ -W -Wall -Werror -ansi -pedantic main.cpp HashTableChain.cpp HashTableProbe.cpp
	./a.out -2 -chain input1.txt
probesimple: main.cpp 
	g++ -W -Wall -Werror -ansi -pedantic main.cpp HashTableChain.cpp HashTableProbe.cpp
	./a.out -1 -probe input1.txt
probespell: main.cpp 
	g++ -W -Wall -Werror -ansi -pedantic main.cpp HashTableChain.cpp HashTableProbe.cpp
	./a.out -2 -probe input1.txt	
clean: 
	rm a.out 